[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = ["forge-std/=node_modules/forge-std/src/", "@latticexyz/=node_modules/@latticexyz/", "@openzeppelin/=node_modules/@openzeppelin/contracts/"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]

[fmt]
ignore = ['**/codegen/**/*.sol']
sort_imports = true
tab_width = 2
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
